### PR TITLE
fix(name-registry): transfer not allowed to 0x0

### LINKED ISSUE #47: Name registry: make it not possible to transfer entry to address 0

### PR DESCRIPTION
**Pull request by ngyam**
Closes #47

### CODE REVIEW

File: test/registry/simple_registry_test.js [hunk 1]
```diff
@@ -211,6 +212,23 @@ contract("SimpleRegistry", accounts => {
...
   });
 
+  it("should not allow to transfer to address 0x0", async () => {
+    let isFailed = false;
+
+    try {
+      await simpleReg.transfer(name, DEFAULT_ADDRESS, {
+        from: accounts[1]
+      });
+      isFaield = true;
```
Comment (danzipie) [inline test/registry/simple_registry_test.js]: fix typo

Comment (ngyam) [reply test/registry/simple_registry_test.js]: I copied that part of code, I corrected it everywhere

**Comment by ngyam** [comment]
@danzipie yoyo
