### PR TITLE
fix(Node Control Lookup): Emit event

### LINKED ISSUE #54: Node control: emit event in case of node control address change in lookup

### PR DESCRIPTION
**Pull request by hai-ko**
closes #54

### CODE REVIEW

File: test/nodecontrol/nodecontrol_lookup_test.js [hunk 1]
```diff
@@ -57,5 +62,10 @@ contract('NodeControlLookUp', function (accounts) {
             await nodeControlLookUp.changeAddress(accounts[6], { from: accounts[1] }).should.be.rejectedWith("Sender is not owner");
             await nodeControlLookUp.changeAddress(accounts[6], { from: owner }).should.be.fulfilled;
         });
+
+        it('must emit event NodeControlAddressChanged correctly', async function () {
```
Comment (ngyam) [inline test/nodecontrol/nodecontrol_lookup_test.js]:
```suggestion
        it('must emit event NewNodeControlAddress correctly', async function () {
```

File: contracts/nodecontrol/NodeControlLookUp.sol [hunk 2]
```diff
@@ -8,11 +8,14 @@ contract NodeControlLookUp is Ownable {
     
     address public nodeControlContract;
 
+    event NewNodeControlAddress(address indexed _newNodeControlAddress);
+
     constructor(address _nodeControlAddress, address _owner)
         public 
     {
         nodeControlContract = _nodeControlAddress;
         _transferOwnership(_owner);
```
Comment (ngyam) [inline contracts/nodecontrol/NodeControlLookUp.sol]:
```suggestion
```

File: contracts/nodecontrol/NodeControlLookUp.sol [hunk 3]
```diff
@@ -8,11 +8,14 @@ contract NodeControlLookUp is Ownable {
     
     address public nodeControlContract;
 
+    event NewNodeControlAddress(address indexed _newNodeControlAddress);
+
     constructor(address _nodeControlAddress, address _owner)
         public 
     {
         nodeControlContract = _nodeControlAddress;
```
Comment (ngyam) [inline contracts/nodecontrol/NodeControlLookUp.sol]:
```suggestion
        _transferOwnership(_owner);
        nodeControlContract = _nodeControlAddress;
```

Comment (ngyam) [reply contracts/nodecontrol/NodeControlLookUp.sol]: Just putting the _transferOwnership before the address assignment and event
